version: "3"
services:
  frontend:
    build:
      context: ./
      dockerfile: ./front/dockerfile
    ports:
      - 4200:4200

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000

networks:
  default:
    name: web_network
    driver: bridge
