FROM node:16.8

WORKDIR /app

COPY package.json /app/
COPY package-lock.json /app/
COPY tsconfig.base.json /app
RUN npm install


COPY ./front/ .
EXPOSE 4200

WORKDIR /app/

CMD ["npm","run", "serve"]
